let items = {
	"General": [
		{vnum: "5", sdesc: "a message post"},
		{vnum: "23", sdesc: "some silk"},
		{vnum: "26", sdesc: "some gem powder"},
		{vnum: "27", sdesc: "a vial of blood"},
		{vnum: "28", sdesc: "a stick of incense"},
		{vnum: "29", sdesc: "some bat guano"},
		{vnum: "33", sdesc: "black poisoning powder"},
		{vnum: "34", sdesc: "a blank scroll"},
		{vnum: "35", sdesc: "a glass flask"},
		{vnum: "36", sdesc: "a note"},
		{vnum: "37", sdesc: "a quill"},
		{vnum: "38", sdesc: "some fur"},
		{vnum: "39", sdesc: "a pile of sand"},
		{vnum: "40", sdesc: "a pinch of sulphur"},
		{vnum: "41", sdesc: "a perfectly smooth stone"},
		{vnum: "42", sdesc: "a piece of smelted metal"},
		{vnum: "44", sdesc: "an elf ear"},
		{vnum: "45", sdesc: "an amulet of communication"},
		{vnum: "46", sdesc: "a starstone"},
		{vnum: "47", sdesc: "a moonstone"},
		{vnum: "48", sdesc: "an earthstone"},
		{vnum: "49", sdesc: "a sunstone"},
		{vnum: "50", sdesc: "a scroll of recall"},
		{vnum: "51", sdesc: "a glass potion bottle of recall"},
		{vnum: "52", sdesc: "a spellbook"},
		{vnum: "53", sdesc: "a bone"},
		{vnum: "54", sdesc: "a piece of string"},
		{vnum: "55", sdesc: "a vial of holy water"},
		{vnum: "56", sdesc: "a flask of water"},
		{vnum: "57", sdesc: "a pinch of phosphorus"},
		{vnum: "58", sdesc: "a candle"},
		{vnum: "59", sdesc: "some holly"},
		{vnum: "60", sdesc: "some mistletoe"},
		{vnum: "61", sdesc: "a flask of oil"},
		{vnum: "62", sdesc: "a piece of bark"},
		{vnum: "63", sdesc: "a feather"},
		{vnum: "64", sdesc: "a crystal rod"},
		{vnum: "65", sdesc: "a scale"},
		{vnum: "66", sdesc: "a small silver mirror"},
		{vnum: "67", sdesc: "a gem"},
		{vnum: "68", sdesc: "a spell pouch"},
		{vnum: "69", sdesc: "a salted piece of meat"},
		{vnum: "73", sdesc: "a small nugget of gold"},
		{vnum: "77", sdesc: "a piece of wood"},
		{vnum: "79", sdesc: "a human head"},
		{vnum: "80", sdesc: "a sea elf ear"},
		{vnum: "81", sdesc: "a brightstone"},
		{vnum: "85", sdesc: "an arrow head"},
		{vnum: "88", sdesc: "a disguise kit"},
		{vnum: "89", sdesc: "some black soot"},
		{vnum: "90", sdesc: "some salt"},
		{vnum: "92", sdesc: "an anvil"},
		{vnum: "93", sdesc: "a red hot forge"},
		{vnum: "94", sdesc: "a smithy's barrel"},
		{vnum: "98", sdesc: "a jewellers hammer"},
		{vnum: "100", sdesc: "adders tongue"},
		{vnum: "101", sdesc: "a green flask of adders tongue infusion"},
		{vnum: "102", sdesc: "an agrimony plant"},
		{vnum: "103", sdesc: "dried agrimony leaves"},
		{vnum: "104", sdesc: "a dark green flask of agrimony infusion"},
		{vnum: "105", sdesc: "an alkanet plant"},
		{vnum: "106", sdesc: "an alkanet root"},
		{vnum: "107", sdesc: "Alkanet root powder"},
		{vnum: "108", sdesc: "powdered rubarb leaf"},
		{vnum: "280", sdesc: "a pinch of powdered iron"},
		{vnum: "281", sdesc: "a black onyx gem"},
		{vnum: "282", sdesc: "a piece of fine silver wire"},
		{vnum: "283", sdesc: "a tiny bell"},
		{vnum: "284", sdesc: "adders stomach"},
		{vnum: "285", sdesc: "powdered animal hoof"},
		{vnum: "286", sdesc: "some dried powdered peas"},
		{vnum: "287", sdesc: "a dart"},
		{vnum: "288", sdesc: "a scorpion tail"},
		{vnum: "289", sdesc: "a minotaur horn"},
		{vnum: "290", sdesc: "a piece of zombie flesh"},
		{vnum: "291", sdesc: "a piece of bettle chitine"},
		{vnum: "292", sdesc: "a snake tongue"},
		{vnum: "293", sdesc: "some crab meat"},
		{vnum: "294", sdesc: "a bear claw"},
		{vnum: "295", sdesc: "a tiny ruby"},
		{vnum: "296", sdesc: "an ettercap fang"},
		{vnum: "297", sdesc: "a wyvern tail"},
		{vnum: "8002", sdesc: "a water trough"},
		{vnum: "8004", sdesc: "a turquoise silk gown"},
		{vnum: "8005", sdesc: "a Jewelled Ladies Dagger"},
		{vnum: "8006", sdesc: "a potion of beauty"},
		{vnum: "8007", sdesc: "a sewing needle"},
		{vnum: "8008", sdesc: "some fine fabric"},
		{vnum: "8009", sdesc: "some silk thread"},
		{vnum: "8012", sdesc: "a pot of rouge"},
		{vnum: "8013", sdesc: "light weight scale mail"},
		{vnum: "8014", sdesc: "calf hide boots"},
		{vnum: "8015", sdesc: "calf hide gloves"},
		{vnum: "8016", sdesc: "calf hide breeches"},
		{vnum: "8017", sdesc: "a calf hide vest"},
		{vnum: "8018", sdesc: "a calf hide cap"},
		{vnum: "8022", sdesc: "blue velveteen breeches"},
		{vnum: "8023", sdesc: "a purple silk robe"},
		{vnum: "8024", sdesc: "polished leather boots"},
		{vnum: "8025", sdesc: "a maroon leather belt"},
		{vnum: "8026", sdesc: "green silk slippers"},
		{vnum: "8027", sdesc: "a black handled broadsword"},
		{vnum: "8028", sdesc: "a black handled dagger"},
		{vnum: "8029", sdesc: "a ladies silk purse"},
		{vnum: "8030", sdesc: "a sturdy shovel"},
		{vnum: "8031", sdesc: "a travellers light"},
		{vnum: "8032", sdesc: "travellers rations"},
		{vnum: "8033", sdesc: "a travellers water skin"},
		{vnum: "8034", sdesc: "a travellers cloak"},
		{vnum: "8035", sdesc: "a travellers boat"},
		{vnum: "8036", sdesc: "a travellers pack"},
		{vnum: "8038", sdesc: "a blue crystal vial of protection"},
		{vnum: "8039", sdesc: "scroll of protection"},
		{vnum: "8041", sdesc: "a white glass vial of Movement"},
		{vnum: "8042", sdesc: "a Scroll of Movement"},
		{vnum: "8043", sdesc: "a purple wizards robe"},
		{vnum: "8044", sdesc: "a purple wizards hat"},
		{vnum: "8045", sdesc: "an ale glass"},
		{vnum: "8046", sdesc: "a hearty stew"},
		{vnum: "8053", sdesc: "a map of Forgotten Kingdoms"},
		{vnum: "8054", sdesc: "a cut glass jar of levitation potion"},
		{vnum: "8055", sdesc: "a levitation scroll"},
		{vnum: "8058", sdesc: "topaz earrings"},
		{vnum: "8060", sdesc: "a leather saddle"},
		{vnum: "8061", sdesc: "some fresh meat"},
		{vnum: "8062", sdesc: "a map of Waterdeep"},
		{vnum: "8063", sdesc: "a map of Hartsvale"},
		{vnum: "8064", sdesc: "a map of Zazesspur"},
		{vnum: "8065", sdesc: "a map of Faerdale"},
		{vnum: "8066", sdesc: "a red cut glass jar of detection"},
		{vnum: "8067", sdesc: "a scroll of detection"},
		{vnum: "8074", sdesc: "a biscuit of hay"},
		{vnum: "8075", sdesc: "a bag of oats"},
		{vnum: "8077", sdesc: "silk stockings"},
		{vnum: "8078", sdesc: "a silk chemise"},
		{vnum: "8079", sdesc: "a fine cotton undershirt"},
		{vnum: "8087", sdesc: "fine wool socks"},
		{vnum: "8088", sdesc: "a red saddle blanket"},
		{vnum: "8089", sdesc: "a leather halter"},
		{vnum: "8090", sdesc: "horse shoes"},
		{vnum: "8094", sdesc: "a fine chainmail belt"},
		{vnum: "8095", sdesc: "a map of Berdusk"},
		{vnum: "8096", sdesc: "a map of Zhentil Keep"},
		{vnum: "8101", sdesc: "a gem encrusted staff"},
		{vnum: "8102", sdesc: "golden chain armour"},
		{vnum: "8103", sdesc: "a set of lock picks"},
		{vnum: "8104", sdesc: "a green cut glass jar of healing"},
		{vnum: "8105", sdesc: "a yellow flowered herb"},
		{vnum: "8106", sdesc: "a jar of crushed pine needles"},
		{vnum: "8108", sdesc: "a low cut blue dress"},
		{vnum: "8109", sdesc: "a small ceramic caraffe of healing"},
		{vnum: "8110", sdesc: "a dish of roast lamb"},
		{vnum: "8111", sdesc: "a glass of white wine"},
		{vnum: "8113", sdesc: "a feathered silk hat"},
		{vnum: "8114", sdesc: "a wide brimmed suede hat"},
		{vnum: "8115", sdesc: "a full helm"},
		{vnum: "8116", sdesc: "a hardened leather helm"},
		{vnum: "8117", sdesc: "a small lute"},
		{vnum: "8118", sdesc: "a small harp"},
		{vnum: "8119", sdesc: "fresh crusty bread"},
		{vnum: "8120", sdesc: "a chocolate cake"},
		{vnum: "8121", sdesc: "a beef pie"},
		{vnum: "8123", sdesc: "fine chain mail armour"},
		{vnum: "8124", sdesc: "a fine chain mail coif"},
		{vnum: "8125", sdesc: "fine chainmail leggings"},
		{vnum: "8126", sdesc: "fine chain mail sleeves"},
		{vnum: "8127", sdesc: "fine chainmail gloves"},
		{vnum: "8128", sdesc: "stitched leather boots"},
		{vnum: "8129", sdesc: "a pearl necklace"},
		{vnum: "8131", sdesc: "a black handled axe"},
		{vnum: "8132", sdesc: "a money purse"},
		{vnum: "8133", sdesc: "embroidered gloves"},
		{vnum: "8134", sdesc: "an embroidered face mask"},
		{vnum: "8135", sdesc: "polished plate armour"},
		{vnum: "8136", sdesc: "a smooth opal"},
		{vnum: "8137", sdesc: "a two-handed sword"},
		{vnum: "8138", sdesc: "a polished metal helm"},
		{vnum: "8139", sdesc: "a polished metal visor"},
		{vnum: "8140", sdesc: "a polished metal shield"},
		{vnum: "8141", sdesc: "a wand of magic missiles"},
		{vnum: "8142", sdesc: "a wand of shield"},
		{vnum: "8143", sdesc: "a wand of fireball"},
		{vnum: "8144", sdesc: "a custard tart"},
		{vnum: "8145", sdesc: "a bottle of milk"},
		{vnum: "8146", sdesc: "some tabacco"},
		{vnum: "8147", sdesc: "a wooden pipe"},
		{vnum: "8148", sdesc: "brown leather shoes"},
		{vnum: "8149", sdesc: "a fox fur collar"},
		{vnum: "8150", sdesc: "rabbit fur boots"},
		{vnum: "8151", sdesc: "an ermine cape"},
		{vnum: "8152", sdesc: "mink lined leggings"},
		{vnum: "8153", sdesc: "a fresh trout"},
		{vnum: "8154", sdesc: "a fresh salmon"},
		{vnum: "8155", sdesc: "a jar of fresh sardines"},
		{vnum: "8156", sdesc: "a scroll of healing"},
		{vnum: "8157", sdesc: "a perky fur hat"},
		{vnum: "8158", sdesc: "a light weight longsword"},
		{vnum: "8159", sdesc: "a red handled dagger"},
		{vnum: "8160", sdesc: "thick heavy rope"},
		{vnum: "8161", sdesc: "a coil of fine rope"},
		{vnum: "8162", sdesc: "a large tuna fish"},
		{vnum: "8163", sdesc: "a smoked salmon"},
		{vnum: "8164", sdesc: "smoked venison"},
		{vnum: "8165", sdesc: "a jar of brine"},
		{vnum: "8166", sdesc: "hide of a deer"},
		{vnum: "8167", sdesc: "hide of a cow"},
		{vnum: "8168", sdesc: "a bag of peanuts"},
		{vnum: "8169", sdesc: "a bag of hazelnuts"},
		{vnum: "8170", sdesc: "rose scented perfume"},
		{vnum: "8171", sdesc: "a pine scented perfume"},
		{vnum: "8172", sdesc: "a simple glass lantern"},
		{vnum: "8173", sdesc: "a golden lantern"},
		{vnum: "8174", sdesc: "a history of waterdeep"},
		{vnum: "8175", sdesc: "a history of tethyr"},
		{vnum: "8176", sdesc: "beef jerky"},
		{vnum: "8177", sdesc: "a hide of a dragon"},
		{vnum: "8178", sdesc: "some knuckle bones"},
		{vnum: "8179", sdesc: "a leather bracer"},
		{vnum: "8180", sdesc: "a black handled morningstar"},
		{vnum: "8181", sdesc: "a tapestry belt"},
		{vnum: "8182", sdesc: "a tapestry skirt"},
		{vnum: "8183", sdesc: "a tapestry cap"},
		{vnum: "8184", sdesc: "a tapestry vest"},
		{vnum: "8185", sdesc: "a leather harness"},
		{vnum: "8186", sdesc: "a large war hammer"},
		{vnum: "8187", sdesc: "green gem stone earrings"},
		{vnum: "8188", sdesc: "a blue sailors hat"},
		{vnum: "8189", sdesc: "a simple gold ring"},
		{vnum: "8190", sdesc: "a book - \"Lloth and the Giant Shoe\""},
		{vnum: "8191", sdesc: "brown leggings"},
		{vnum: "8192", sdesc: "a green tunic"},
		{vnum: "8193", sdesc: "a brown leather belt"},
		{vnum: "8194", sdesc: "a book - \"The Battle Queen\""},
		{vnum: "8196", sdesc: "green wool sleeves"},
		{vnum: "8197", sdesc: "a keg of ale"},
		{vnum: "8199", sdesc: "a map of Menzoberranzan"},
		{vnum: "8201", sdesc: "a blunt dagger"},
		{vnum: "8202", sdesc: "a battered mace"},
		{vnum: "8203", sdesc: "a blunt longsword"},
		{vnum: "8204", sdesc: "a book - \"Farewell to the Flame-Haired Lady\""},
		{vnum: "8205", sdesc: "a book - \"Return of the Flame-Haired Lady\""},
		{vnum: "8206", sdesc: "a book - \"A Tear for Cormanthor\""},
		{vnum: "8207", sdesc: "a book - \"A Song of Sune's Mercy\""},
		{vnum: "8208", sdesc: "a bottle of frost wine"},
		{vnum: "8209", sdesc: "a bottle of Marsember Blush"},
		{vnum: "8210", sdesc: "a mug of stagheart boug mead"},
		{vnum: "8211", sdesc: "a bottle of Luskan Stout"},
		{vnum: "8212", sdesc: "a bottle of Cormyran Brandy"},
		{vnum: "8213", sdesc: "a mug of knee cracker cider"},
		{vnum: "8214", sdesc: "a shot of Kuldahar Tree Sap"},
		{vnum: "8215", sdesc: "a mug of Arrowflight Ale"},
		{vnum: "8216", sdesc: "a mug of Fiddlebenders Mystery Brew"},
		{vnum: "8217", sdesc: "a buckskin quiver"},
		{vnum: "8218", sdesc: "a plain leather scabbard"},
		{vnum: "8219", sdesc: "a blue flowered herb"},
		{vnum: "8220", sdesc: "a glass of Zzar"},
		{vnum: "8221", sdesc: "a mug of Rivengut"},
		{vnum: "8222", sdesc: "a glass of sherry"},
		{vnum: "8223", sdesc: "a flask of apricot brandy"},
		{vnum: "8224", sdesc: "a flask of sparkling evermead"},
		{vnum: "8225", sdesc: "a mug of moonshae moonshine"},
		{vnum: "8226", sdesc: "a small glass of Elquesstria"},
		{vnum: "8227", sdesc: "a travel biscuit"},
		{vnum: "8228", sdesc: "a blue-green diaphanous gown"},
		{vnum: "8229", sdesc: "a green velvet cape"},
		{vnum: "8230", sdesc: "a jade green coat"},
		{vnum: "8231", sdesc: "jade green trousers"},
		{vnum: "8232", sdesc: "multi-coloured glitter"},
		{vnum: "8234", sdesc: "an ivory ring"},
		{vnum: "8235", sdesc: "a book - \"The Snow Queen's Daughter\""},
		{vnum: "8236", sdesc: "a book - \"The Day of the missing E's\""},
		{vnum: "8237", sdesc: "a book - \"The Shadows and the Lady\""},
		{vnum: "8238", sdesc: "a book - \"The Question Answered\""},
		{vnum: "8239", sdesc: "a book - \"Bard's Wisdom\""},
		{vnum: "8240", sdesc: "a book - \"Haunted Memories\""},
		{vnum: "8241", sdesc: "a book - \"The Ballad of Old Bards\""},
		{vnum: "8242", sdesc: "a brass buckle"},
		{vnum: "8248", sdesc: "an ivory broach"},
		{vnum: "8249", sdesc: "reinforced leather gloves"},
		{vnum: "8250", sdesc: "a riding whip"},
		{vnum: "8251", sdesc: "a short red cape"},
		{vnum: "8252", sdesc: "a gold brocade vest"},
		{vnum: "8253", sdesc: "flimsy gold brocade shoes"},
		{vnum: "8254", sdesc: "kid gloves"},
		{vnum: "8255", sdesc: "a green silk doublet"},
		{vnum: "8256", sdesc: "a floppy hat"},
		{vnum: "8257", sdesc: "brilliant crimson hose"},
		{vnum: "8258", sdesc: "a long red full skirt"},
		{vnum: "8259", sdesc: "a fitted breast piece"},
		{vnum: "8260", sdesc: "tight green silk sleeves"},
		{vnum: "8261", sdesc: "a white knee length dress"},
		{vnum: "8262", sdesc: "purple and pink slashed sleeves"},
		{vnum: "8263", sdesc: "a tight fitting gold vest"},
		{vnum: "8264", sdesc: "soft black velvet slippers"},
		{vnum: "8265", sdesc: "a gold turban wrap"},
		{vnum: "8266", sdesc: "canvas knee britches"},
		{vnum: "8267", sdesc: "an apron with pockets"},
		{vnum: "8268", sdesc: "a cloak of midnight blue"},
		{vnum: "8269", sdesc: "wooden clogs"},
		{vnum: "8270", sdesc: "hot buttered snails in steaming valgrath wine"},
		{vnum: "8271", sdesc: "a book - \"The Diary of Amalthea\""},
		{vnum: "8272", sdesc: "fresh strawberries"},
		{vnum: "8273", sdesc: "some clean bandages"},
		{vnum: "8288", sdesc: "a book - \"Lukan's History and Geography of the North\""},
		{vnum: "8289", sdesc: "a book - \"Myth Drannor\""},
		{vnum: "8290", sdesc: "a book - \"The Time of Troubles\""},
		{vnum: "8291", sdesc: "a dark blue mask trimmed with silver stars"},
		{vnum: "8292", sdesc: "a dark blue silk tunic edged with silver"},
		{vnum: "8293", sdesc: "a narrow silver circlet studded with sapphires"},
		{vnum: "8294", sdesc: "dark blue tight leather breeches"},
		{vnum: "8295", sdesc: "dark blue suede boots"},
		{vnum: "8296", sdesc: "dark blue silk sleeves"},
		{vnum: "8297", sdesc: "dark blue fingerless gloves"},
		{vnum: "8298", sdesc: "a silver bracer studded with sapphires"},
		{vnum: "8299", sdesc: "a silver bracer studded with pearls"},
		{vnum: "8300", sdesc: "a silver war axe with a blue handle"},
		{vnum: "8301", sdesc: "blue leather moccasins"},
		{vnum: "8302", sdesc: "blue steel vambraces"},
		{vnum: "8303", sdesc: "blue steel greaves"},
		{vnum: "8304", sdesc: "a silver bastard sword with a blue handle"},
		{vnum: "8305", sdesc: "a silver stringed harp"},
		{vnum: "8306", sdesc: "a silver stringed lyre"},
		{vnum: "8307", sdesc: "a silver studded set of drums"},
		{vnum: "8308", sdesc: "a white and silver studded leather bustier"},
		{vnum: "8309", sdesc: "white and silver studded leather sleeves"},
		{vnum: "8310", sdesc: "amethyst earrings"},
		{vnum: "8311", sdesc: "an amethyst necklace"},
		{vnum: "8312", sdesc: "white and silver studded leather leggings"},
		{vnum: "8313", sdesc: "white and silver studded leather boots"},
		{vnum: "8314", sdesc: "white fur boots"},
		{vnum: "8315", sdesc: "white silk sleeves"},
		{vnum: "8316", sdesc: "a white lace dress"},
		{vnum: "8317", sdesc: "white silk slippers"},
		{vnum: "8318", sdesc: "a studded blue leather scabbard"},
		{vnum: "8319", sdesc: "a heavy silver scabbard"},
		{vnum: "8321", sdesc: "a midnight blue shirt"},
		{vnum: "8322", sdesc: "a silver wrist sheath"},
		{vnum: "8323", sdesc: "a studded leather wrist sheath"},
		{vnum: "8324", sdesc: "white leather gloves"},
		{vnum: "8325", sdesc: "a silver embossed belt"},
		{vnum: "8326", sdesc: "a white and silver studded belt"},
		{vnum: "8327", sdesc: "a gold circlet"},
		{vnum: "8328", sdesc: "a silver circlet"},
		{vnum: "8329", sdesc: "a gem studded silver circlet"},
		{vnum: "8330", sdesc: "black and white breeches"},
		{vnum: "8331", sdesc: "a black and white tunic"},
		{vnum: "8332", sdesc: "black and white sleeves"},
		{vnum: "8333", sdesc: "a black and white cloak"},
		{vnum: "8339", sdesc: "red studded leather armour"},
		{vnum: "8340", sdesc: "blue studded leather sleeves"},
		{vnum: "8341", sdesc: "blue studded leather breeches"},
		{vnum: "8342", sdesc: "a crimson doublet"},
		{vnum: "8343", sdesc: "blue silk pants"},
		{vnum: "8344", sdesc: "blue silk tights"},
		{vnum: "8345", sdesc: "red studded leather boots"},
		{vnum: "8346", sdesc: "a golden silk sash"},
		{vnum: "8347", sdesc: "a red studded leather belt"},
		{vnum: "8348", sdesc: "red and blue slashed sleeves"},
		{vnum: "8349", sdesc: "red leather sleeves"},
		{vnum: "8350", sdesc: "red silk sleeves"},
		{vnum: "8351", sdesc: "red wool sleeves"},
		{vnum: "8352", sdesc: "gold chainmail sleeves"},
		{vnum: "8353", sdesc: "gold silk sleeves"},
		{vnum: "8354", sdesc: "gold thread woollen sleeves"},
		{vnum: "8355", sdesc: "gold trimmed black silk sleeves"},
		{vnum: "8356", sdesc: "a red leather belt"},
		{vnum: "8357", sdesc: "a red silk belt"},
		{vnum: "8360", sdesc: "a ruby encrusted circlet"},
		{vnum: "8361", sdesc: "blue silk sleeves"},
		{vnum: "8362", sdesc: "black scalemail armour"},
		{vnum: "8363", sdesc: "gleaming silver scalemail armour"},
		{vnum: "8364", sdesc: "thin gold hoop earrings"},
		{vnum: "8365", sdesc: "a smooth golden mask with upturned ends"},
		{vnum: "8366", sdesc: "a fitted gold brocade side-laced bodice"},
		{vnum: "8367", sdesc: "a gem studded gold circlet with a linen veil"},
		{vnum: "8368", sdesc: "a floor length kirtle of white silk"},
		{vnum: "8369", sdesc: "gold dusted tiny white silk slippers"},
		{vnum: "8370", sdesc: "white silk gloves"},
		{vnum: "8371", sdesc: "an embossed gold ring"},
		{vnum: "8372", sdesc: "dagged gold trimmed sleeves with a train"},
		{vnum: "8373", sdesc: "a floor length slim gold brocade tie"},
		{vnum: "8374", sdesc: "pearl studded slender golden bracelets"},
		{vnum: "8375", sdesc: "gold trimmed purple hose"},
		{vnum: "8376", sdesc: "purple silk pants"},
		{vnum: "8377", sdesc: "gold silk pants"},
		{vnum: "8378", sdesc: "a silver cod piece"},
		{vnum: "8379", sdesc: "a white aketon"},
		{vnum: "8380", sdesc: "an arming doublet"},
		{vnum: "8381", sdesc: "a leather crinet"},
		{vnum: "8382", sdesc: "a shining silver cuirass"},
		{vnum: "8383", sdesc: "gold trimmed purple leather pants"},
		{vnum: "8386", sdesc: "a mug of robust winter ale"},
		{vnum: "8402", sdesc: "glittering sapphire drop earrings"},
		{vnum: "8403", sdesc: "a glittering sapphire studded silver bracelet"},
		{vnum: "8404", sdesc: "a hunting cloak of forest green"},
		{vnum: "8405", sdesc: "soft doe skin boots"},
		{vnum: "8406", sdesc: "a black and white belt"},
		{vnum: "8407", sdesc: "a pure white bracer"},
		{vnum: "8408", sdesc: "a pure white ring"},
		{vnum: "8409", sdesc: "a forest green velvet gown"},
		{vnum: "8410", sdesc: "blue studded leather armour"},
		{vnum: "8411", sdesc: "a blue cotton tunic"},
		{vnum: "8412", sdesc: "a blue cotton pants"},
		{vnum: "8413", sdesc: "a blue studded leather belt"},
		{vnum: "8414", sdesc: "a leather belt pouch"},
		{vnum: "8415", sdesc: "a sapphire necklace"},
		{vnum: "8416", sdesc: "a black and white bracer"},
		{vnum: "8417", sdesc: "a pure black ring"},
		{vnum: "8418", sdesc: "a coonskin hat"},
		{vnum: "8419", sdesc: "leather chaps"},
		{vnum: "8420", sdesc: "rough quilted tunic"},
		{vnum: "8421", sdesc: "leather scale armour"},
		{vnum: "8422", sdesc: "wooden splint armour"},
		{vnum: "8423", sdesc: "lamellar armour"},
		{vnum: "8424", sdesc: "cord armour"},
		{vnum: "8425", sdesc: "armour of bone"},
		{vnum: "8426", sdesc: "spiked leather armour"},
		{vnum: "8427", sdesc: "elk hide armour"},
		{vnum: "8428", sdesc: "scale mail armour"},
		{vnum: "8429", sdesc: "brigandine armor"},
		{vnum: "8430", sdesc: "leather ring mail"},
		{vnum: "8431", sdesc: "a brass studded targe"},
		{vnum: "8432", sdesc: "a hide buckler"},
		{vnum: "8433", sdesc: "a bark scutum"},
		{vnum: "8434", sdesc: "a hide kite shield"},
		{vnum: "8435", sdesc: "a grey felt hat"},
		{vnum: "8436", sdesc: "a quilted coif"},
		{vnum: "8437", sdesc: "a straw hat"},
		{vnum: "8438", sdesc: "80)a pair of crampons"},
		{vnum: "8439", sdesc: "climbing gloves"},
		{vnum: "8440", sdesc: "a sheepskin vest"},
		{vnum: "8441", sdesc: "a wolf hide headdress"},
		{vnum: "8442", sdesc: "a dark green baladrana"},
		{vnum: "8443", sdesc: "a brown leather baldric"},
		{vnum: "8444", sdesc: "leather hiking boots"},
		{vnum: "8445", sdesc: "leather riding boots"},
		{vnum: "8446", sdesc: "stout canvas pants"},
		{vnum: "8447", sdesc: "a tan leather cassock"},
		{vnum: "8448", sdesc: "a wool poncho"},
		{vnum: "8449", sdesc: "elk hide gamash"},
		{vnum: "8450", sdesc: "a woven garnache"},
		{vnum: "8451", sdesc: "rabbitskin gloves"},
		{vnum: "8452", sdesc: "wool mittens"},
		{vnum: "8453", sdesc: "archery gloves"},
		{vnum: "8454", sdesc: "a light cotton surcoat"},
		{vnum: "8455", sdesc: "a simple cotton tunic"},
		{vnum: "8456", sdesc: "snowshoes"},
		{vnum: "8457", sdesc: "a leather bandana"},
		{vnum: "8458", sdesc: "a heavy winter blanket"},
		{vnum: "8459", sdesc: "a saddle blanket"},
		{vnum: "8460", sdesc: "leather-bound hide boots"},
		{vnum: "8461", sdesc: "an antlered helm"},
		{vnum: "8462", sdesc: "the clawed headband"},
		{vnum: "8463", sdesc: "a rough hide backpack"},
		{vnum: "8464", sdesc: "a squirrel skin beltpouch"},
		{vnum: "8465", sdesc: "a wicker pack"},
		{vnum: "8466", sdesc: "a canvas sack"},
		{vnum: "8467", sdesc: "a fancy stitched leather quiver"},
		{vnum: "8468", sdesc: "a scroll case"},
		{vnum: "8469", sdesc: "dark leather saddlebags"},
		{vnum: "8470", sdesc: "an elkhorn knife"},
		{vnum: "8471", sdesc: "an adze"},
		{vnum: "8472", sdesc: "a hatchet"},
		{vnum: "8473", sdesc: "a wooden cudgel"},
		{vnum: "8474", sdesc: "an iron shod quarterstaff"},
		{vnum: "8475", sdesc: "a wooden mallet"},
		{vnum: "8476", sdesc: "a birch longbow"},
		{vnum: "8477", sdesc: "a birch shortbow"},
		{vnum: "8478", sdesc: "a logging axe"},
		{vnum: "8479", sdesc: "a great scimitar"},
		{vnum: "8480", sdesc: "a steel scimitar"},
		{vnum: "8481", sdesc: "a steel spear"},
		{vnum: "8482", sdesc: "a boar spear"},
		{vnum: "8483", sdesc: "a sickle"},
		{vnum: "8484", sdesc: "a scythe"},
		{vnum: "8485", sdesc: "a bullwhip"},
		{vnum: "8486", sdesc: "an axe of bone"},
		{vnum: "8487", sdesc: "a bone club"},
		{vnum: "8488", sdesc: "a toothed club"},
		{vnum: "8489", sdesc: "a bone knife"},
		{vnum: "8490", sdesc: "an iron mace"},
		{vnum: "8491", sdesc: "a bladebacked mace"},
		{vnum: "8492", sdesc: "a steel bastard sword"},
		{vnum: "8493", sdesc: "a steel broadsword"},
		{vnum: "8494", sdesc: "a gladius"},
		{vnum: "8495", sdesc: "a steel shortsword"},
		{vnum: "8496", sdesc: "a steel warhammer"},
		{vnum: "8497", sdesc: "a hammer"},
		{vnum: "8498", sdesc: "a steel cutlass"},
		{vnum: "8499", sdesc: "a steel rapier"},
		{vnum: "8500", sdesc: "a worn wooden staff"},
		{vnum: "8501", sdesc: "a silver sickle"},
		{vnum: "8502", sdesc: "a tendrilled quarterstaff"},
		{vnum: "8503", sdesc: "rabbit jerky"},
		{vnum: "8504", sdesc: "smoked trout"},
		{vnum: "8505", sdesc: "wild purple grapes"},
		{vnum: "8506", sdesc: "a dirty potato"},
		{vnum: "8507", sdesc: "a wild brown onion"},
		{vnum: "8508", sdesc: "a loaf of whole wheat bread"},
		{vnum: "8509", sdesc: "a bowl of squirrel stew"},
		{vnum: "8510", sdesc: "a fried rabbit"},
		{vnum: "8511", sdesc: "a roast boar"},
		{vnum: "8512", sdesc: "a big orange carrot"},
		{vnum: "8513", sdesc: "a bowl of turnip stew"},
		{vnum: "8514", sdesc: "a plate of flapjacks"},
		{vnum: "8515", sdesc: "some deer sausages"},
		{vnum: "8516", sdesc: "a mushroom omelette"},
		{vnum: "8517", sdesc: "a hunk of yellow cheese"},
		{vnum: "8518", sdesc: "a jar of honey"},
		{vnum: "8519", sdesc: "a plate of liver and onions"},
		{vnum: "8520", sdesc: "an apple dumpling"},
		{vnum: "8521", sdesc: "a red apple"},
		{vnum: "8522", sdesc: "a rubarb pie"},
		{vnum: "8523", sdesc: "a cherry tart"},
		{vnum: "8524", sdesc: "a waterhorn"},
		{vnum: "8525", sdesc: "a cup of coffee"},
		{vnum: "8526", sdesc: "a cup of tea"},
		{vnum: "8527", sdesc: "a coffee pot"},
		{vnum: "8528", sdesc: "a tea jar"},
		{vnum: "8529", sdesc: "a jug of moonshine"},
		{vnum: "8530", sdesc: "a mug of wheat beer"},
		{vnum: "8531", sdesc: "a healing poultice"},
		{vnum: "8532", sdesc: "a frying pan"},
		{vnum: "8533", sdesc: "a signal whistle"},
		{vnum: "8534", sdesc: "a bull horn"},
		{vnum: "8535", sdesc: "a mouth harp"},
		{vnum: "8536", sdesc: "flint and steel"},
		{vnum: "8537", sdesc: "an iron pot"},
		{vnum: "8538", sdesc: "a whetstone"},
		{vnum: "8539", sdesc: "a canvas tent"},
		{vnum: "8540", sdesc: "a corncob pipe"},
		{vnum: "8541", sdesc: "an ivory merschausm"},
		{vnum: "8542", sdesc: "a hickory pipe"},
		{vnum: "8543", sdesc: "a ceramic pipe"},
		{vnum: "8544", sdesc: "a staghorn pipe"},
		{vnum: "8545", sdesc: "a marble pipe"},
		{vnum: "8546", sdesc: "a torch"},
		{vnum: "8547", sdesc: "a tin lantern"},
		{vnum: "8548", sdesc: "falconer's gloves"},
		{vnum: "8549", sdesc: "a yellow glass jar of invisibility"},
		{vnum: "8550", sdesc: "a pink glass jar of strength"},
		{vnum: "8551", sdesc: "a moon shaped bottle of refresh"},
		{vnum: "8552", sdesc: "a book - \"A Blue Moon Not At All\""},
		{vnum: "8553", sdesc: "a book - \"Precious Things\""},
		{vnum: "8554", sdesc: "a book - \"Far Shores\""},
		{vnum: "8555", sdesc: "a book - \"Fire in the Sky\""},
		{vnum: "8556", sdesc: "a book - \"The Mage Fair\""},
		{vnum: "8557", sdesc: "a book - \"Megan and the Merman\""},
		{vnum: "8558", sdesc: "a book - \"Tymora's Love\""},
		{vnum: "8559", sdesc: "a book - \"The Siren Queen\""},
		{vnum: "8560", sdesc: "a book - \"The Sorcerous Boon\""},
		{vnum: "8561", sdesc: "a book - \"A Maiden's Lament\""},
		{vnum: "8562", sdesc: "a book - \"Hawks and Eagles\""},
		{vnum: "8563", sdesc: "a book - \"The Harp\""},
		{vnum: "8564", sdesc: "a book - \"The Making of a New Boss\""},
		{vnum: "8565", sdesc: "a book - \"The Finding\""},
		{vnum: "8566", sdesc: "a book - \"Briasma's Ballad\""},
		{vnum: "8567", sdesc: "a leather weapons harness"},
		{vnum: "8568", sdesc: "a fletching knife"},
		{vnum: "8569", sdesc: "a string of cat gut"},
		{vnum: "8570", sdesc: "some beeswax"},
		{vnum: "8571", sdesc: "a hot smithy's forge"},
		{vnum: "8572", sdesc: "a pure black bracer"},
		{vnum: "8573", sdesc: "a book - \"The Making of a Just Knight\""},
		{vnum: "8574", sdesc: "a book - \"Tale of a True Knight\""},
		{vnum: "8575", sdesc: "a book - \"A Squires Lesson\""},
		{vnum: "8576", sdesc: "a book - \"The Travelling Squire\""},
		{vnum: "8577", sdesc: "a book - \"The Squire and the Beast\""},
		{vnum: "8578", sdesc: "a book - \"A winterfest story\""},
		{vnum: "8586", sdesc: "spiced dried potato slices"},
		{vnum: "8587", sdesc: "a book - \"Arialle's story\""},
		{vnum: "8597", sdesc: "a fake moustache"},
		{vnum: "8598", sdesc: "a barrette"},
		{vnum: "8599", sdesc: "a gold shirt"},
		{vnum: "8600", sdesc: "gold pants"},
		{vnum: "8601", sdesc: "gold sleeves"},
		{vnum: "8602", sdesc: "gold gloves"},
		{vnum: "8603", sdesc: "gold shoes"},
		{vnum: "8604", sdesc: "a nondescript leather armour"},
		{vnum: "8605", sdesc: "a nondescript leather armour"},
		{vnum: "8606", sdesc: "nondescript leather breeches"},
		{vnum: "8607", sdesc: "a tabard with projecting ornamented shoulder plates"},
		{vnum: "8610", sdesc: "open-meshwork point-toed boots"},
		{vnum: "8611", sdesc: "a red silk cumberbund"},
		{vnum: "8616", sdesc: "an Adventurer's Guide"},
		{vnum: "8617", sdesc: "a glass of sword coast foam"},
		{vnum: "8621", sdesc: "a book - \"The Basilisk\""},
		{vnum: "8622", sdesc: "a book - \"Shadows\""},
		{vnum: "8623", sdesc: "a book - \"The Saddest Thing\""},
		{vnum: "8624", sdesc: "a book - \"Ashes\""},
		{vnum: "8625", sdesc: "a book - \"The trial of Aserak\""},
		{vnum: "8626", sdesc: "a book - \"Da Book od Schlem\""},
		{vnum: "8627", sdesc: "a book - \"Beauty and the Beast\""},
		{vnum: "8628", sdesc: "a book - \"Time\""},
		{vnum: "8629", sdesc: "a book - \"Fairy Lover\""},
		{vnum: "8630", sdesc: "a book - \"A paladin, a drow and some elves.\""},
		{vnum: "8631", sdesc: "a book - \"The Tale of Sir Tocla\""},
		{vnum: "8632", sdesc: "a book - \"The pursuit of Knowledge.\""},
		{vnum: "8633", sdesc: "a book - \"Summer Rain\""},
		{vnum: "8634", sdesc: "a book - \"A red eagle takes wing\""},
		{vnum: "8635", sdesc: "a book - \"Manshoon and the Abyss.\""},
		{vnum: "8636", sdesc: "a book - \"Jewels of the Sun, the Moon and the Sea\""},
		{vnum: "8637", sdesc: "a book - \"Yakun's Story\""},
		{vnum: "8638", sdesc: "a book - \"Guardians\""},
		{vnum: "8639", sdesc: "a book - \"Sea Mist\""},
		{vnum: "8640", sdesc: "a book - \"Scarlet Mother of Moonlight\""},
		{vnum: "8641", sdesc: "a book - \"The Gift\""},
		{vnum: "8642", sdesc: "a book - \"Straw in to Gold\""},
		{vnum: "8643", sdesc: "a book - \"The Dragon Song\""},
		{vnum: "8644", sdesc: "a book - \"The Long Road\""},
		{vnum: "8645", sdesc: "a book - \"A Lament of the Sea\""},
		{vnum: "8646", sdesc: "a book - \"Wedding Song\""},
		{vnum: "8647", sdesc: "a book - \"Midsummer\""},
		{vnum: "8648", sdesc: "a book - \"Riddles\""},
		{vnum: "8649", sdesc: "a book - \"Dawn\""},
		{vnum: "8650", sdesc: "a book - \"A Thief's Tale\""},
		{vnum: "8651", sdesc: "a book - \"Spread Your Wings And Fly\""},
		{vnum: "8658", sdesc: "a book - \"Reflections\""},
		{vnum: "8659", sdesc: "a book - \"Gywdion's Courting\""},
		{vnum: "8660", sdesc: "a book - \"The squire and the maiden\""},
		{vnum: "8661", sdesc: "a book - \"A Thunderstorm's Demon\""},
		{vnum: "8662", sdesc: "a book - \"Syren's Book of Rhymes\""},
		{vnum: "8663", sdesc: "a birch arrow"},
		{vnum: "8664", sdesc: "a smithys hammer"},
		{vnum: "8665", sdesc: "a book - \"The Ballad of Urborg\""},
		{vnum: "8666", sdesc: "a book - \"The Ballad of Mortis Bane\""},
		{vnum: "8667", sdesc: "a book - \"The Ballad of Sarvas Taravel\""},
		{vnum: "8668", sdesc: "a book - \"The Top Ten Things Not To Say To A Priest Of Cyric\""},
		{vnum: "8669", sdesc: "a book - \"Crimson Tides \""},
		{vnum: "8670", sdesc: "a book - \"The Unicorn\""},
		{vnum: "8671", sdesc: "a book - \"Misty Overture\""},
		{vnum: "8672", sdesc: "a book - \"The Ballad of Selionair\""},
		{vnum: "8673", sdesc: "a book - \"The might of Talos\""},
		{vnum: "8674", sdesc: "a book - \"Introduction to the planes\""},
		{vnum: "8678", sdesc: "a book - \"Time Renews Tomorrow\""},
		{vnum: "8676", sdesc: "a book - \"The Ballad of Waterdeep\""},
		{vnum: "8679", sdesc: "a book - \"Dragons\""},
		{vnum: "8680", sdesc: "a book - \"The Tale of Lady Anne\""},
		{vnum: "8681", sdesc: "a book - \"Helm, God of Guardians\""},
		{vnum: "8682", sdesc: "a book - \"Taverns\""},
		{vnum: "8683", sdesc: "a book - \"Thoughts\""},
		{vnum: "8684", sdesc: "a book - \"The Ballad of Lyle\""},
		{vnum: "8685", sdesc: "a book - \"All For Me Ale\""},
		{vnum: "8686", sdesc: "a book - \"Heartache\""},
		{vnum: "8687", sdesc: "a book - \"The Day of the Missing E's, the Play\""},
		{vnum: "8688", sdesc: "a book - \"Nonsensical Limericks for a Cold Evening\""},
		{vnum: "8689", sdesc: "a book - \"The Tailor's Tale\""},
		{vnum: "8690", sdesc: "a book - \"Warrior Maid\""},
		{vnum: "8691", sdesc: "a book - \"Farewell\""},
		{vnum: "8692", sdesc: "a book - \"Lies\""},
		{vnum: "8693", sdesc: "a book - \"Remember\""},
		{vnum: "8694", sdesc: "a book - \"Swords and Silk\""},
		{vnum: "8695", sdesc: "a book - \"Dance With Me\""},
		{vnum: "8696", sdesc: "a book - \"The Language of Love\""},
		{vnum: "8697", sdesc: "a book - \"Heart's Choices\""},
		{vnum: "8698", sdesc: "a book - \"Nightmares\""},
		{vnum: "8699", sdesc: "a book - \"Introduction to Isaldur\""},
		{vnum: "8700", sdesc: "a book - \"Isaldur's Song\""},
		{vnum: "8701", sdesc: "a book - \"The Staff of Tymora\""},
		{vnum: "8702", sdesc: "a book - \"Grass Shores\""},
		{vnum: "8703", sdesc: "a book - \"Harbouring Hopes\""},
		{vnum: "8704", sdesc: "a book - \"On the Shores of Tomorrow\""},
		{vnum: "8705", sdesc: "a book - \"I See You Everywhere\""},
		{vnum: "8706", sdesc: "a book - \"You've Never Met My Mom\""},
		{vnum: "8707", sdesc: "a book - \"Dance of the Trees\""},
		{vnum: "8708", sdesc: "a book - \"Cities\""},
		{vnum: "8709", sdesc: "a book - \"A Netherese Tale\""},
		{vnum: "8710", sdesc: "a book - \"Child of Strife\""},
		{vnum: "8711", sdesc: "a book - \"Sacred Ground\""},
		{vnum: "8712", sdesc: "a book - \"Heart's Home\""},
		{vnum: "8713", sdesc: "a book - \"Chilling Touch\""},
		{vnum: "8714", sdesc: "a book - \"Happy Thoughts About Loviatar\""},
		{vnum: "8715", sdesc: "a book - \"Life and Death and Time\""},
		{vnum: "8716", sdesc: "a book - \"Wyrmling\""},
		{vnum: "8717", sdesc: "a book - \"Forest Poem\""},
		{vnum: "8718", sdesc: "a book - \"Beware the Raven\""},
		{vnum: "8719", sdesc: "a book - \"The Storm\""},
		{vnum: "8720", sdesc: "a book - \"Dragon Poem\""},
		{vnum: "8721", sdesc: "a book - \"The Constellations of Toril\""},
		{vnum: "8722", sdesc: "a book - \"Cat in the Hat\""},
		{vnum: "8723", sdesc: "a book - \"Day and Night\""},
		{vnum: "8724", sdesc: "a book - \"Ceara\""},
		{vnum: "8725", sdesc: "a book - \"Blackbirds\""},
		{vnum: "8726", sdesc: "a book - \"Twilight Grey\""},
		{vnum: "8727", sdesc: "a book - \"Riddles\""},
		{vnum: "8728", sdesc: "a book - \"No Hero\""},
		{vnum: "8729", sdesc: "a book - \"Dryad Song\""},
		{vnum: "8730", sdesc: "a book - \"The Witch of Westmere Land\""},
		{vnum: "8731", sdesc: "a book - \"Saying Goodbye\""},
		{vnum: "8732", sdesc: "a book - \"Journey\""},
		{vnum: "8733", sdesc: "a book - \"Ten Steps to a Good Polymorph\""},
		{vnum: "8734", sdesc: "a book - \"False Hope\""},
		{vnum: "8735", sdesc: "a book - \"Ballad of Lone Wolf\""},
		{vnum: "8736", sdesc: "a book - \"Every Dog Has His Day\""},
		{vnum: "8737", sdesc: "a book - \"Limericks\""},
		{vnum: "8738", sdesc: "a book - \"Lord of Battles\""},
		{vnum: "8739", sdesc: "a book - \"The Early Morning Rain\""},
		{vnum: "8740", sdesc: "a book - \"Taboo\""},
		{vnum: "8741", sdesc: "a book - \"The Folley of Zhar\""},
		{vnum: "8742", sdesc: "a book - \"Our Lady of Spells\" of Heleyn\""},
		{vnum: "8743", sdesc: "a book - \"The day of a scribe\""},
		{vnum: "8744", sdesc: "a book - \"Ode to Connor\""},
		{vnum: "8745", sdesc: "a book - \"Connor\""},
		{vnum: "8746", sdesc: "a book - \"The Price of Duty\""},
		{vnum: "8747", sdesc: "a book - \"Bards Just Want To Have Fun\""},
		{vnum: "8748", sdesc: "a book - \"The Sewer Cleaners\""},
		{vnum: "8749", sdesc: "a book - \"Dartose and the Dragons\""},
		{vnum: "8750", sdesc: "a book - \"The Tale of Valakas\""},
		{vnum: "8751", sdesc: "a book - \"The Dawning\""},
		{vnum: "8752", sdesc: "a book - \"Meama's Song\""},
		{vnum: "8753", sdesc: "a book - \"Nivek's Song\""},
		{vnum: "8754", sdesc: "a book - \"Hope\""},
		{vnum: "8755", sdesc: "a book - \"Hartsvale's Queen\""},
		{vnum: "8756", sdesc: "a book - \"Connor's Song\""},
		{vnum: "8757", sdesc: "a book - \"Faces\""},
		{vnum: "8758", sdesc: "a book - \"I Believe\""},
		{vnum: "8759", sdesc: "a book - \"Swordmaster and Son\""},
		{vnum: "8760", sdesc: "a book - \"Lady Who Watches The Griffons\""},
		{vnum: "8761", sdesc: "a book - \"Deadly Performance\""},
		{vnum: "8762", sdesc: "a book - \"A Man With No Gods\""},
		{vnum: "8763", sdesc: "a book - \"Quintel's Tale\""},
		{vnum: "8764", sdesc: "a book - \"Two Poems\" by Syren"},
		{vnum: "8765", sdesc: "a book - \"A Collection of Poems\" by Laurie Moonheart"},
		{vnum: "8766", sdesc: "a book - \"Apart No More\" by Myarenir"},
		{vnum: "8767", sdesc: "a book - \"A Collection of Songs, Volume One\" by Sparlow"},
		{vnum: "8768", sdesc: "a book - \"A Collection of Songs, Volume Two\" by Sparlow"},
		{vnum: "8769", sdesc: "a book - \"Isaldur's Song\" by Sparlow"},
		{vnum: "8770", sdesc: "a book - \"Returning\" by Sparlow"},
		{vnum: "8771", sdesc: "a book - \"Two Poems\" by Ciara Tearnan"},
		{vnum: "8772", sdesc: "a book - \"Songs of Silver\" by Lorelie"},
		{vnum: "8773", sdesc: "a book - \"Songs of the West\" by Lorelie"},
		{vnum: "8774", sdesc: "a book - \"A Collection of Poems\" by Vierdis"},
		{vnum: "8775", sdesc: "a book - \"Wishes and Fear\" by Hearin"},
		{vnum: "8776", sdesc: "a book - \"Freedom\" by Lorelie"},
		{vnum: "8777", sdesc: "a book - \"Treasure\" by Lorelie"},
		{vnum: "8778", sdesc: "a book - \"Namaarie\" by Lorelie"},
		{vnum: "8779", sdesc: "a book - \"Immortality\" by Reece"},
		{vnum: "8780", sdesc: "a book - \"Mystery's Blade\" by Kylivo"},
		{vnum: "8781", sdesc: "a book - \"Rasen and the Magic Spoon\" by Reece"},
		{vnum: "8782", sdesc: "a book - \"Reece's Waterdeep Traveler's Guide\" by Reece"},
		{vnum: "8783", sdesc: "a book - \"Garl and the Evil Kobolds\" by Japcil"},
		{vnum: "8784", sdesc: "a book - \"Forever\" by Alelynn"},
		{vnum: "8785", sdesc: "a book - \"Little Priest\" by Ciara"},
		{vnum: "8786", sdesc: "a book - \"Faces of Waterdeep\" by Rainer Alycari"},
		{vnum: "8787", sdesc: "a book - \"Inspiration\" by Rainer"},
		{vnum: "8788", sdesc: "a book - \"Silent Rain\" by Rainer"},
		{vnum: "8789", sdesc: "a book - \"Sky Staring Rainer\" by Mele"},
		{vnum: "8790", sdesc: "a book - \"Why She Weeps\" by Mele"},
		{vnum: "8791", sdesc: "a book - \"Father Of Mine\" by Mele"},
		{vnum: "8792", sdesc: "a book - \"Ode To Jinx\" by Mele"},
		{vnum: "8793", sdesc: "a book - \"Alone\" by Minalde"},
		{vnum: "8794", sdesc: "a book - \"Darkness\" by Minalde"},
		{vnum: "8795", sdesc: "a book - \"Epitaph\" by Minalde"},
		{vnum: "8796", sdesc: "a book - \"Storm\" by Minalde"},
		{vnum: "8797", sdesc: "a book - \"Journey of Enlightenment\" by Wynne"},
		{vnum: "8798", sdesc: "a book - \"Treasure Tricks\" by Nytte"},
		{vnum: "8799", sdesc: "a book - \"Midnight Wings\" by Lorelie"},
		{vnum: "8800", sdesc: "a book - \"Darkness Falls\" by Lorelie"},
		{vnum: "8801", sdesc: "a book - \"A Song of the Sea\" by Adsartha"},
		{vnum: "8802", sdesc: "a book - \"Dreaming\" by Lorelie"},
		{vnum: "8803", sdesc: "a book - \"Love and Time\" by Adsartha"},
		{vnum: "8804", sdesc: "a book - \"Page to Paladin: Morality\" by Andreas"},
		{vnum: "8805", sdesc: "a book - \"Page to Paladin: Riches\" by Andreas"},
		{vnum: "8806", sdesc: "a book - \"For Fun\" by Reece"},
		{vnum: "8807", sdesc: "a book - \"In My Own Words\" by Summer"},
		{vnum: "8808", sdesc: "a book - \"Tales of the Kingdoms\" by Lorelie"},
		{vnum: "8809", sdesc: "a book - \"Songs of Hope\" by Lorelie"},
		{vnum: "8810", sdesc: "a book - \"Elven History\" by Penryn"},
		{vnum: "8811", sdesc: "a book - \"A Collection of Elven Tales\" by Penryn"},
		{vnum: "8812", sdesc: "a book - \"Songs of Dreams\" by Lorelie"},
		{vnum: "8813", sdesc: "a book - \"I Am There\" by Nysan"},
		{vnum: "8814", sdesc: "a book - \"Lorelie's Song\" by Isaldur"},
		{vnum: "8815", sdesc: "a book - \"Symphony of Lies\" by Isaldur"},
		{vnum: "8816", sdesc: "a book - \"Sable and Company\" by Isaldur"},
		{vnum: "8817", sdesc: "a book - \"Forest Poems\" by Valia"},
		{vnum: "8818", sdesc: "a book - \"Tales of the Moon\" by Lorelie"},
		{vnum: "8819", sdesc: "a book - \"Strife, Death, and Murder\" by Lorelie"},
		{vnum: "8820", sdesc: "a book - \"The Nature of Diseases\" by Kylikka"},
		{vnum: "8821", sdesc: "a book - \"Ahskahala Durothil\" by Penryn"},
		{vnum: "8822", sdesc: "a book - \"Two Poems - Storm and Pain\" by Caidi Stormfyre"},
		{vnum: "8823", sdesc: "a book - \"Solaghar Q'Xorlarrin's Guide to the Surface, Book 1\""},
		{vnum: "8824", sdesc: "a book - \"A History of the Northern Sword Coast by Summer\""},
		{vnum: "8825", sdesc: "a book - \"A History of Ixinos by Summer\""},
		{vnum: "8826", sdesc: "a book - \"Important Events of Ixinos by Summer\""},
		{vnum: "8827", sdesc: "a book - \"On The Usefulness of Plants by Faris\""},
		{vnum: "8828", sdesc: "a book - \"Three Poems by Mele\""},
		{vnum: "8829", sdesc: "a book - \"The Herbs of Faerun, Book One by Summer\""},
		{vnum: "8830", sdesc: "a book - \"The Herbs of Faerun, Book Two by Summer\""},
		{vnum: "8831", sdesc: "a book - \"The Priestess and the Boy by Isamir\""},
		{vnum: "8832", sdesc: "a book - \"Ode to the Nameless Warrior by Darmeth\""},
		{vnum: "8833", sdesc: "a book - \"Pirates of the Trackless Sea by Sanin\""},
		{vnum: "8834", sdesc: "a book - \"A Day in the Life of an Orc by Siros\""},
		{vnum: "8835", sdesc: "a book - \"A Song for Helm by Starling\""},
		{vnum: "8836", sdesc: "a book - \"Service to the Father by Randuil\""},
		{vnum: "8837", sdesc: "a book - \"Songs by Starling\""},
		{vnum: "8838", sdesc: "a book - \"A Collection by Mirabai\""},
		{vnum: "8839", sdesc: "a book - \"Music of the Mad by Mirabai\""},
		{vnum: "8840", sdesc: "a book - \"A Collection of Words by Mirabai\""},
		{vnum: "8841", sdesc: "a book - \"Silversong by Mirabai\""},
		{vnum: "8842", sdesc: "a book - \"Teaching Lessons by Tandria\""},
		{vnum: "8843", sdesc: "a book - \"A Warrior's Heart by Timaeus\""},
		{vnum: "8844", sdesc: "a book - \"Bards by Sanin\""},
		{vnum: "8845", sdesc: "a book - \"Summer's Sonnet by Sanin\""},
		{vnum: "8846", sdesc: "a book - \"Chasing Mother's Tears by Syren\""},
		{vnum: "8847", sdesc: "a book - \"The Ghost of the One Black Eye by Mirabai\""},
		{vnum: "8848", sdesc: "a book - \"A Collection of Songs by Mirabai\""},
		{vnum: "8849", sdesc: "a book - \"Poems by Rotha\""},
		{vnum: "8850", sdesc: "a book - \"Dangerous Lands by Janon\""},
		{vnum: "8851", sdesc: "a book - \"Summer by Shog\""},
		{vnum: "8852", sdesc: "a book - \"Two Poems by Jeroldo\""},
		{vnum: "8853", sdesc: "a book - \"A Collection of Songs, Volume 3 by Sparlow Lellwyn\""},
		{vnum: "8854", sdesc: "a book - \"A Collection of Songs, Volume 4 by Sparlow Lellwyn\""},
		{vnum: "8855", sdesc: "a book - \"Granel's Song by Sparlow\""},
		{vnum: "8856", sdesc: "a book - \"The Tale of Jacob by Jarek\""},
		{vnum: "8857", sdesc: "a book - \"Running Away by Summer\""},
		{vnum: "8858", sdesc: "a book - \"The Ranger Code by Janon\""},
		{vnum: "8859", sdesc: "a book - \"Ranger Duties by Janon\""},
		{vnum: "8860", sdesc: "a book - \"Ranger History by Janon\""},
		{vnum: "8861", sdesc: "a book - \"The Order of Rangers by Janon\""},
		{vnum: "8862", sdesc: "a book - \"Father of the Elves by Lenowe\""},
		{vnum: "8863", sdesc: "a book - \"Nature Poems by Telk\""},
		{vnum: "8864", sdesc: "a book - \"Exer's Hymn by Mira Mockingbird\""},
		{vnum: "8865", sdesc: "a book - \"Red Roses by Pepe\""},
		{vnum: "8866", sdesc: "a book - \"Songs From A Bardic Life by Estrild\""},
		{vnum: "8867", sdesc: "a book - \"The Price of Arrogance by Telk\""},
		{vnum: "8868", sdesc: "a book - \"A Guide to Nobility Rank and Etiquette by Elvoriel Evra\""},
		{vnum: "8869", sdesc: "a book - \"The Hunt by Tychina\""},
		{vnum: "8870", sdesc: "a book - \"Full Tummies And Warm Hearts Cook Book by Pibbs\""},
		{vnum: "8871", sdesc: "a book - \"Scouting and Combat by Valyn\""},
		{vnum: "8872", sdesc: "a book - \"Page to Paladin: Faith\" by Andreas"},
		{vnum: "8873", sdesc: "a book - \"Legends of Helmite Saints\" by Andreas"},
		{vnum: "8874", sdesc: "a book - \"Tested and True\" by Andreas"},
		{vnum: "8875", sdesc: "a book - \"Moonlight's Triumph\" by Mintiper Moonsilver"},
	],
	"Forage": [
		{vnum: "39000", sdesc: "a plum tree"},
		{vnum: "39001", sdesc: "a juicy purple plum"},
		{vnum: "39002", sdesc: "a tall apple tree"},
		{vnum: "39003", sdesc: "a pear tree"},
		{vnum: "39004", sdesc: "a raspberry bush"},
		{vnum: "39005", sdesc: "a ripe red raspberry"},
		{vnum: "39006", sdesc: "a blueberry bush"},
		{vnum: "39007", sdesc: "a ripe blueberry"},
		{vnum: "39008", sdesc: "a strawberry plant"},
		{vnum: "39009", sdesc: "a ripe red strawberry"},
		{vnum: "39010", sdesc: "a peach tree"},
		{vnum: "39011", sdesc: "a kiwi vine"},
		{vnum: "39012", sdesc: "a ripe kiwi"},
		{vnum: "39013", sdesc: "a grape vine"},
		{vnum: "39014", sdesc: "a bunch of green grapes"},
		{vnum: "39015", sdesc: "a bunch of purple grapes"},
		{vnum: "39016", sdesc: "a cherry tree"},
		{vnum: "39017", sdesc: "a cluster of cherries"},
		{vnum: "39018", sdesc: "an apricot tree"},
		{vnum: "39019", sdesc: "a nectarine tree"},
		{vnum: "39020", sdesc: "a ripe nectarine"},
		{vnum: "39021", sdesc: "a lemon tree"},
		{vnum: "39022", sdesc: "a fig tree"},
		{vnum: "39023", sdesc: "a ripe fig"},
		{vnum: "39024", sdesc: "a banana tree"},
		{vnum: "39025", sdesc: "a ripe yellow banana"},
		{vnum: "39026", sdesc: "an orange tree"},
		{vnum: "39027", sdesc: "a ripe juicy orange"},
		{vnum: "39028", sdesc: "an olive tree"},
		{vnum: "39029", sdesc: "a green olive"},
		{vnum: "39030", sdesc: "a black olive"},
		{vnum: "39031", sdesc: "a tomato vine"},
		{vnum: "39032", sdesc: "a blackberry vine"},
		{vnum: "39033", sdesc: "a ripe juicy blackberry"},
		{vnum: "39034", sdesc: "a watermelon vine"},
		{vnum: "39035", sdesc: "a large watermelon"},
	]
}

let mobs = {
	"General": [
		{vnum: "80", sdesc: "a bugbear"},
		{vnum: "81", sdesc: "a kobold"},
		{vnum: "82", sdesc: "a hill giant"},
		{vnum: "84", sdesc: "a harpy"},
		{vnum: "100", sdesc: "a bear"},
		{vnum: "101", sdesc: "a crocodile"},
		{vnum: "102", sdesc: "an ettercap"},
		{vnum: "103", sdesc: "a gibberling"},
		{vnum: "104", sdesc: "a gnoll"},
		{vnum: "105", sdesc: "a goblin"},
		{vnum: "106", sdesc: "a griffon"},
		{vnum: "107", sdesc: "a hobgoblin"},
		{vnum: "108", sdesc: "a lizard man"},
		{vnum: "109", sdesc: "a wild stag"},
		{vnum: "110", sdesc: "a cow"},
		{vnum: "111", sdesc: "an ogre"},
		{vnum: "112", sdesc: "an orc"},
		{vnum: "113", sdesc: "a remorhaz"},
		{vnum: "114", sdesc: "a rat"},
		{vnum: "115", sdesc: "a sahuagin"},
		{vnum: "116", sdesc: "a skeleton"},
		{vnum: "117", sdesc: "a snake"},
		{vnum: "118", sdesc: "a giant spider"},
		{vnum: "119", sdesc: "a stirge"},
		{vnum: "120", sdesc: "a thri-kreen"},
		{vnum: "121", sdesc: "a troll"},
		{vnum: "122", sdesc: "a whale"},
		{vnum: "123", sdesc: "a wyvern"},
		{vnum: "124", sdesc: "a yeti"},
		{vnum: "125", sdesc: "a shark"},
		{vnum: "126", sdesc: "a lamia"},
		{vnum: "127", sdesc: "a bandit"},
	],
	"Forage": [
		{vnum: "39000", sdesc: "a grey rabbit"},
		{vnum: "39001", sdesc: "a white rabbit"},
		{vnum: "39002", sdesc: "a brown hare"},
		{vnum: "39003", sdesc: "a wild goose"},
		{vnum: "39004", sdesc: "a wild pheasant hen"},
		{vnum: "39005", sdesc: "a fan-tailed turkey"},
		{vnum: "39008", sdesc: "a moorhen"},
		{vnum: "39009", sdesc: "a yellowbill duck"},
		{vnum: "39010", sdesc: "a drab grouse"},
		{vnum: "39011", sdesc: "a wood pigeon"},
		{vnum: "39012", sdesc: "a ground hog"},
		{vnum: "39013", sdesc: "a pink-bellied sow"},
		{vnum: "39014", sdesc: "a tusked boar"},
		{vnum: "39015", sdesc: "a roe deer"},
		{vnum: "39016", sdesc: "an enormous elk"},
		{vnum: "39017", sdesc: "a cariboo"},
		{vnum: "39018", sdesc: "a young moose"},
		{vnum: "39019", sdesc: "a cotton-tail antelope"},
		{vnum: "39020", sdesc: "a mountain goat"},
		{vnum: "39021", sdesc: "a mountain goat"},
		{vnum: "39022", sdesc: "a long haired sheep"},
		{vnum: "39023", sdesc: "a curlicue-horned ram"},
		{vnum: "39024", sdesc: "a long eared rabbit"},
		{vnum: "39025", sdesc: "a striped possum"},
		{vnum: "39026", sdesc: "a wild red squirrel"},
		{vnum: "39027", sdesc: "a muskrat"},
		{vnum: "39028", sdesc: "a broad-tailed beaver"},
		{vnum: "39029", sdesc: "an otter"},
		{vnum: "39030", sdesc: "a pink flamingo"},
		{vnum: "39031", sdesc: "a striped polecat"},
		{vnum: "39032", sdesc: "a stoat"},
		{vnum: "39033", sdesc: "a wildebeest"},
		{vnum: "39034", sdesc: "a tawny lion"},
		{vnum: "39035", sdesc: "a wild brumby"},
		{vnum: "39036", sdesc: "a timber wolf"},
		{vnum: "39037", sdesc: "a desert elephant"},
		{vnum: "39038", sdesc: "a mighty condor"},
		{vnum: "39039", sdesc: "a zebra"},
		{vnum: "39040", sdesc: "a gazelle"},
		{vnum: "39041", sdesc: "a bottle-nosed dolphin"},
		{vnum: "39042", sdesc: "a whiskered sealion"},
		{vnum: "39043", sdesc: "enormous walrus"},
		{vnum: "39044", sdesc: "a penguin"},
		{vnum: "39045", sdesc: "a polar bear"}
	]
}

export function items_library(area_items) {
    return [
        {title: "Area", list:area_items},
        {title: "General", list:items.General},
        {title: "Forage", list:items.Forage},
    ]
}

export function mobs_library(area_mobs) {
    return [
        {title: "Area", list:area_mobs},
        {title: "General", list:mobs.General},
        {title: "Forage", list:mobs.Forage},
    ]
}